# Generated by Django 6.0.1 on 2026-01-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('bldgrp', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('div', models.CharField(choices=[('dhaka', 'Dhaka'), ('chattogram', 'Chattogram'), ('rajshahi', 'Rajshahi'), ('khulna', 'Khulna'), ('barishal', 'Barishal'), ('sylhet', 'Sylhet'), ('rangpur', 'Rangpur'), ('mymensingh', 'Mymensingh')], max_length=20)),
                ('dist', models.CharField(max_length=50)),
                ('nid', models.CharField(max_length=20, unique=True)),
                ('birthdate', models.DateField()),
                ('profession', models.CharField(max_length=100)),
                ('lastdonationdate', models.DateField()),
                ('diabetes', models.BooleanField(default=False)),
                ('hypertension', models.BooleanField(default=False)),
                ('heartdisease', models.BooleanField(default=False)),
                ('asthma', models.BooleanField(default=False)),
                ('kidneydisease', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
