# Generated by Django 6.0.1 on 2026-01-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.EmailField(blank='True', default='', max_length=254, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='donor',
            name='none',
            field=models.BooleanField(default=False),
        ),
    ]
