# Generated by Django 6.0.1 on 2026-01-30 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_remove_donor_created_at_remove_donor_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='dist',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='div',
            new_name='division',
        ),
    ]
