# Generated by Django 6.0.1 on 2026-01-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_rename_dist_donor_district_rename_div_donor_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='division',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chattogram', 'Chattogram'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Barishal', 'Barishal'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh')], max_length=20),
        ),
    ]
