# Generated by Django 6.0.1 on 2026-01-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_alter_donor_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='division',
            field=models.CharField(choices=[('dhaka', 'Dhaka'), ('chattogram', 'Chattogram'), ('rajshahi', 'Rajshahi'), ('khulna', 'Khulna'), ('barishal', 'Barishal'), ('sylhet', 'Sylhet'), ('rangpur', 'Rangpur'), ('mymensingh', 'Mymensingh')], max_length=20),
        ),
    ]
