# Generated by Django 6.0.1 on 2026-01-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_alter_donor_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.EmailField(default='', max_length=254, null='True', unique='True'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=models.CharField(max_length=15, unique='True'),
        ),
    ]
