# Generated by Django 6.0.1 on 2026-02-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0006_alter_donor_email_alter_donor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
