# Generated by Django 6.0.1 on 2026-02-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0007_donor_gender_alter_donor_email_alter_donor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='age',
            field=models.IntegerField(blank=True, default=18, null=True),
        ),
    ]
