# Generated by Django 6.0.1 on 2026-02-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0008_donor_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
