# Generated by Django 6.0.1 on 2026-03-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0009_donor_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='hiv',
            field=models.BooleanField(default=False),
        ),
    ]
