# Generated by Django 6.0.1 on 2026-03-06 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0010_donor_hiv'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='nid',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='profession',
        ),
        migrations.AddField(
            model_name='donor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_bio', to=settings.AUTH_USER_MODEL),
        ),
    ]
