# Generated by Django 6.0.1 on 2026-03-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0011_remove_donor_birthdate_remove_donor_nid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='searchdonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bloodbag', models.IntegerField(blank=True, default=1, null=True)),
                ('bldgrp', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('division', models.CharField(choices=[('dhaka', 'Dhaka'), ('chattogram', 'Chattogram'), ('rajshahi', 'Rajshahi'), ('khulna', 'Khulna'), ('barishal', 'Barishal'), ('sylhet', 'Sylhet'), ('rangpur', 'Rangpur'), ('mymensingh', 'Mymensingh')], max_length=20)),
                ('district', models.CharField(max_length=50)),
            ],
        ),
    ]
