# Generated by Django 6.0.1 on 2026-03-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0012_searchdonor'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='address',
            field=models.CharField(default='', max_length=300),
        ),
    ]
