# Generated by Django 6.0.1 on 2026-03-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0013_donor_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='asthma',
        ),
        migrations.AddField(
            model_name='donor',
            name='h_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='searchdonor',
            name='hlocation',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='searchdonor',
            name='num',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
