# Generated by Django 6.0.1 on 2026-03-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0014_remove_donor_asthma_donor_h_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdonor',
            name='urgency',
            field=models.CharField(choices=[('asap', 'Emergency'), ('custom', 'Non-urgent')], max_length=30, null=True),
        ),
    ]
