# Generated by Django 6.0.1 on 2026-03-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0015_searchdonor_urgency'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdonor',
            name='request_at',
            field=models.DateField(null=True),
        ),
    ]
