# Generated by Django 6.0.1 on 2026-03-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0016_searchdonor_request_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdonor',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
