# Generated by Django 6.0.1 on 2026-03-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0017_searchdonor_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdonor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
