# Generated by Django 6.0.1 on 2026-04-15 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0018_searchdonor_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='lastdonationdate',
            new_name='donation_date',
        ),
    ]
