# Generated by Django 6.0.1 on 2026-04-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0019_rename_lastdonationdate_donor_donation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
