# Generated by Django 6.0.1 on 2026-04-19 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0020_alter_donor_donation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='diabetes',
            new_name='hep',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='heartdisease',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='kidneydisease',
        ),
    ]
