# Generated by Django 6.0.1 on 2026-04-19 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0021_rename_diabetes_donor_hep_remove_donor_heartdisease_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='none',
            new_name='no_disease',
        ),
    ]
