# Generated by Django 6.0.1 on 2026-05-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0022_rename_none_donor_no_disease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='weight',
        ),
        migrations.AlterField(
            model_name='donor',
            name='age',
            field=models.DateField(blank=True, null=True),
        ),
    ]
