# Generated by Django 6.0.1 on 2026-05-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0023_remove_donor_address_remove_donor_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='area',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='postcode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='upazila',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
