# Generated by Django 6.0.1 on 2026-06-01 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0024_donor_area_donor_postcode_donor_upazila'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchdonor',
            name='bloodbag',
        ),
        migrations.RemoveField(
            model_name='searchdonor',
            name='hlocation',
        ),
        migrations.RemoveField(
            model_name='searchdonor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='searchdonor',
            name='request_at',
        ),
        migrations.RemoveField(
            model_name='searchdonor',
            name='urgency',
        ),
    ]
